from ff import *


CONSTS_FILE = 'FixTheFence/consts.h'
SOURCE_FILE = 'FixTheFence/FixTheFence.cpp'
SUBMISSION_FILE = 'submission.cpp'


with open(CONSTS_FILE, 'w') as consts:
    for i in range(1, 6):
        prop = Propagator(i)
        assert all(t is None for t in prop.index_topo[0])
        print>>consts, 'const int NUM_TOPOS_%d = %d;' % (prop.h, len(prop.index_topo))
        print>>consts, 'const unsigned transition_data_%d[] = {' % prop.h
        position = 0
        starts = []
        for i in range(len(prop.index_topo)):
            for gate_pair in GATE_PAIRS:
                ts = prop.transition_table[i].get(gate_pair, {})
                starts.append(position)
                position += len(ts)
                for xor_bits, new_topo in ts.items():
                    print>>consts, '%d,' % (xor_bits | (new_topo << 8)),
                print>>consts
        starts.append(position)
        print>>consts, '42};'
        print>>consts, 'const int transition_starts_%d[] = {' % prop.h
        print>>consts, ', '.join(map(str, starts))
        print>>consts, '};'


text = open(SOURCE_FILE).read()
text = text.replace('int main', 'int main1')
text = text.replace('#include "consts.h"', open(CONSTS_FILE).read())
text = '/* ff.py: \n' + open('ff.py').read() + '*'+'/\n' + text
text = '/* generated by this script \n' + open(__file__).read() + '*'+'/\n' + text

with open(SUBMISSION_FILE, 'w') as submission:
    submission.write(text)
